[package]
name = "toml2json"
description = "Convert TOML to JSON"
version = "1.0.0"
authors = ["William Woodruff <william@yossarian.net>"]
edition = "2018"
homepage = "https://github.com/woodruffw/toml2json"
readme = "README.md"
keywords = ["cli"]
categories = ["command-line-utilities"]

[dependencies]
anyhow = "1.0"
clap = "3.0.0-beta.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.5.8"
